# Generated by Django 2.2.7 on 2019-12-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='idea',
            name='idea_link',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='idea',
            name='suggested_by',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
